# Generated by Django 4.1.7 on 2023-03-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_Name',
            new_name='first_name',
        ),
    ]
